
FROM maven:3.9.7-eclipse-temurin-21-alpine as build

LABEL authors="usman"

WORKDIR /home/usr/app

COPY pom.xml .

RUN mvn -B -C dependency:go-offline

COPY src ./src

RUN mvn -B -C clean package -DskipTests

FROM eclipse-temurin:21-jre-alpine

ENV HOME=/home/usr/app

WORKDIR $HOME

COPY --from=build $HOME/target/*.jar .

ENTRYPOINT ["java", "-jar", "cicd-workflow-0.0.1-SNAPSHOT.jar"]
