
FROM eclipse-temurin:21-jdk-alpine AS build
LABEL authors="usman"
WORKDIR /home/usr/app
COPY .mvn/ .mvn
COPY mvnw pom.xml ./
RUN ./mvnw -B -C dependency:go-offline
COPY src ./src
RUN ./mvnw -B -C clean package -DskipTests

FROM eclipse-temurin:21-jre-alpine
ENV HOME=/home/usr/app
WORKDIR $HOME
RUN addgroup -S cicd-workflow-group && adduser -S cicd-workflow-user -G cicd-workflow-group
USER cicd-workflow-user:cicd-workflow-group
COPY --from=build $HOME/target/*.jar .
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "cicd-workflow-0.0.1-SNAPSHOT.jar"]
