
name: CICD_WORKFLOW_PIPELINE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:

      - name: Root login
        run: sudo -i

      - name: Clean up workspace
        run: sudo rm -rf ${{ github.workspace }}/*

      - uses: actions/checkout@v4

      - name: Remove previous docker image
        run: docker rmi usman243/cicd-workflows || true

      - name: Build & restart docker-compose
        run: docker-compose up -d --build

      - name: Exit root user
        run: su - ubuntu
